version: '3'

services:
  postgres_gotan:
    container_name: gotan_container
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gotan_city
    volumes:
       - postgis:/data/postgis
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
    postgis: